//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dosh.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dosh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Display this help screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00001 {
            get {
                return ResourceManager.GetString("CLI_00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display version information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00002 {
            get {
                return ResourceManager.GetString("CLI_00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00003 {
            get {
                return ResourceManager.GetString("CLI_00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00004 {
            get {
                return ResourceManager.GetString("CLI_00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00005 {
            get {
                return ResourceManager.GetString("CLI_00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00006 {
            get {
                return ResourceManager.GetString("CLI_00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00007 {
            get {
                return ResourceManager.GetString("CLI_00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00008 {
            get {
                return ResourceManager.GetString("CLI_00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00100 {
            get {
                return ResourceManager.GetString("CLI_00100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permission denied. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00101 {
            get {
                return ResourceManager.GetString("CLI_00101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; directory creation failed. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00102 {
            get {
                return ResourceManager.GetString("CLI_00102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test identification directory does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00103 {
            get {
                return ResourceManager.GetString("CLI_00103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .dosh.yml file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00104 {
            get {
                return ResourceManager.GetString("CLI_00104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to parse the .dosh.yml file. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CLI_00105 {
            get {
                return ResourceManager.GetString("CLI_00105", resourceCulture);
            }
        }
    }
}
